/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : string,
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PortfolioProject {
  'id' : string,
  'client' : string,
  'title' : string,
  'briefDescription' : string,
  'outcomes' : string,
  'imageUrl' : string,
  'category' : string,
  'fullDescription' : string,
  'techStack' : Array<string>,
}
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getPortfolioProjects' : ActorMethod<[], Array<PortfolioProject>>,
  'getProjectById' : ActorMethod<[string], [] | [PortfolioProject]>,
  'submitContact' : ActorMethod<
    [string, string, string, string, string],
    ContactSubmission
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];