/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const PortfolioProject = IDL.Record({
  'id' : IDL.Text,
  'client' : IDL.Text,
  'title' : IDL.Text,
  'briefDescription' : IDL.Text,
  'outcomes' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'fullDescription' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getPortfolioProjects' : IDL.Func([], [IDL.Vec(PortfolioProject)], ['query']),
  'getProjectById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortfolioProject)],
      ['query'],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const PortfolioProject = IDL.Record({
    'id' : IDL.Text,
    'client' : IDL.Text,
    'title' : IDL.Text,
    'briefDescription' : IDL.Text,
    'outcomes' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'fullDescription' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getPortfolioProjects' : IDL.Func(
        [],
        [IDL.Vec(PortfolioProject)],
        ['query'],
      ),
    'getProjectById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortfolioProject)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };